name: "elixir_bot"
author: "clszzyh"
description: "A Github Bot by Elixir."
branding:
  icon: code
  color: gray-dark
inputs:
  github:
    description: "Github Object"
    default: ${{ toJson(github) }}
    required: false
  report_issue:
    description: "Report Error By Create Issue"
    default: "true"
    required: false
  token:
    description: "Github Token"
    default: ${{ github.token }}
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/clszzyh/elixir_bot:main"
